<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>Range Employee 1000 to 1500</h1>
        <div>a microframework for PHP</div>
        <table border="1">
            <thead>
                <th>Name</th>
                <th>Email</th>
                <th>Position</th>
                <th>Salary</th>
                <th>Ver</th>
            </thead>
            <tbody>
                <?php foreach($jstr as $employee):?>
                <tr>
                    <td><?php echo $employee->name;?></td>
                    <td><?php echo $employee->email;?></td>
                    <td><?php echo $employee->position;?></td>
                    <td><?php echo $employee->salary;?></td>
                    <td><a href="http://localhost/slim/public/ver/<?php echo $employee->id; ?>">Ver</a></td>
                </tr>
                <?php endforeach;?>                
            </tbody>
        </table>
        <a href="http://localhost/slim/public/listado/">Back!!!...</a>
    </body>
</html>
